# Generated by Django 5.2.7 on 2025-11-26 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_moneda_usuario_alter_usuario_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='borrado',
        ),
        migrations.AlterField(
            model_name='moneda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monedas', to=settings.AUTH_USER_MODEL),
        ),
    ]
