# Generated by Django 5.2.7 on 2025-10-21 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gasto', '0001_initial'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasto.item'),
        ),
    ]
