# Generated by Django 5.2.7 on 2025-11-03 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0001_initial'),
        ('usuario', '0002_moneda_usuario_borrado_usuario_limite_gasto_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.moneda'),
        ),
    ]
