# Generated by Django 5.2.7 on 2025-11-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_delete_perfil'),
    ]

    operations = [
    ]
